### ISSUE TITLE
2x2 display for containers with more than one item type

### ISSUE THREAD

**Issue by nmay231** [Dr-Turtle/Baro-StorageIcons#1]
As we discussed in the steam community channel, it would be nice to show the first four item types in a storage container if there is more than one. I've already started skimming through the code.

I'll see if there's a way to combine sprites into one sprite since that would require minimal changes to the cache object and such.

Worse comes to worst, I think having a "+" or "..." to indicate more item types would be helpful. But I have confidence I can get the 2x2 grid working. :)

**Comment by Dr-Turtle** [comment]
It might be worthwhile to add the '+' or '...' (I prefer '+') indicator even if you get 2x2 working, some people (especially those with small monitors) may prefer it.

**Comment by Dr-Turtle** [comment]
misclick

**Comment by nmay231** [comment]
Missed this comment. I'll add a config option for the + indicator.
